<header>
	<div class="fleft">
		<a href="/"><img alt="affordable websites" title="Starfish Internet Solutions" src="/Project/1_Website/Design/Panels/header/images/spmiLogo.png" /></a>
		<p>FIBER, OUR STRENGTH</p>
	</div>
	<section class="fright clearfix">
		<?= navigation::displayNavigationForPages('secondary')?>
	</section>
	<section class="fright clearfix">
			<?= navigation::displayNavigationForPages('primary','','',true); ?>
	</section>	
</header>