<div class="bannerContainer mBxl clearfix">
	<div id="fiberImg"<?=$this->displayElement('image_bg')?>>
		<div id="blueWrap">
			<h1><?=$this->displayElement('page_title_element')?></h1>
		</div>
	</div>
</div>
<div class="lowerPanel clearfix">
	<div class="productContainer clearfix">
		<?=$this->displayElement('page_content_editor_abaca')?>
	</div>
	<div class="productContainer clearfix">
		<?=$this->displayElement('page_content_editor_sisal')?>
	</div>
	<div class="productContainer clearfix">
		<?=$this->displayElement('page_content_editor_jute')?>
	</div>
</div>