<div class="clearfix pBl">
	<div id="contactDetails" class="fleft clearfix">
		<div id="contactHeader" class="clearfix">
			<h1>&#x8054;&#x7CFB;&#x6211;&#x4EEC;</h1>
		</div>
			<hr>
		<div id="contactContent" class="clearfix">
			<h6>&#x4E3B;&#x516C;&#x53F8;&#x5730;&#x5740;</h6>
			<div class="mLxxl mVl clearfix">
				<span id="address" class="fleft mRm mTxs"></span>
				<p>358 Quezon Avenue<br />
				Quezon City<br />
				Philippines, 1113</p>
				<span id="telephoneNo" class="fleft mRm mTxs"></span>
				<br />
				<p>+632.254.27.38 </p>
				<br />
				<span id="emailLogo" class="fleft mRm mTxs"></span>
				<br />
				<p>spmi@spmi-pulp.com</p>
			</div>
			<h6>&#x5236;&#x9020;&#x5730;&#x5740;</h6>
				<p>&#x96F7;&#x8FEA;&#x5C9B;&#x7701;&#x5317;&#x8D1D;&#x9547;</p>
		</div>
		<div id="map" class="clearfix">
			<div id="googleMap">
			
			</div>
			<hr>
			<p>Baybay&#xFF0C;&#x83F2;&#x5F8B;&#x5BBE;&#x83B1;&#x7279;&#x5C9B;&#xFF0C;&#x4F4D;&#x4E8E;&#x6211;&#x4EEC;&#x56FD;&#x5BB6;&#x7684;&#x6700;&#x5148;&#x8FDB;&#x7684;&#x8BBE;&#x65BD;&#x3002;&#x5382;&#x4F4D;&#x4E8E;&#x4EA4;&#x901A;&#x4FBF;&#x5229;&#xFF0C;&#x77ED;&#x77ED;&#x4E24;&#x4E2A;&#x5C0F;&#x65F6;&#x7684;&#x8DEF;&#x7A0B;&#xFF0C;&#x4ECE;&#x5BBF;&#x96FE;&#x5E02;&#x7684;&#x4E3B;&#x8981;&#x56FD;&#x9645;&#x6E2F;&#x53E3;&#x548C;&#x4E09;&#x4E2A;&#x5C0F;&#x65F6;&#x7684;&#x65C5;&#x884C;&#x65F6;&#x95F4;&#x4ECE;&#x83F2;&#x5F8B;&#x5BBE;&#x9996;&#x90FD;&#x9A6C;&#x5C3C;&#x62C9;&#xFF0C;</p>
		</div>
	</div>
	<div id="formWrap" class="fleft clearfix">
		<div id="contactForm" class="clearfix">
			<p>&#x5982;&#x679C;&#x60A8;&#x6709;SPMI&#x6216;&#x4EA7;&#x54C1;&#x7684;&#x4EFB;&#x4F55;&#x7591;&#x95EE;&#xFF0C;&#x8BF7;&#x968F;&#x65F6;&#x968F;&#x610F;&#x586B;&#x5199;&#x4E0B;&#x9762;&#x6240;&#x6709;&#x7684;&#x7A7A;&#x683C;&#x3002;&#x6211;&#x4EEC;&#x5C06;&#x5F88;&#x9AD8;&#x5174;&#x542C;&#x5230;&#x60A8;&#x7684;&#x58F0;&#x97F3;</p>
			<form id="contact_form" method="post" action="/cn/contact-us">
				<input type="hidden" name="status" value="<?=$this->getStatus()?>"/>
				<p><span>&#x516C;&#x53F8;&#x540D;&#x79F0;</span></p><input type="text" name="companyName">
				<p><span>&#x8054;&#x7CFB;&#x4EBA;*</span></p><input type="text" name="contactPerson">
				<p><span>&#x5730;&#x5740;</span></p><input type="text" name="streetAddress">
				<p><span id="city">&#x57CE;&#x5E02;</span></p><input type="text" name="city">
				<p><span id="state">&#x5DDE;</span></p><input type="text" name="state">
				<p><span>&#x56FD;&#x5BB6;</span></p>
				<select name="country">
					<option value="">Country...</option>
					<option value="Afganistan">Afghanistan</option>
					<option value="Albania">Albania</option>
					<option value="Algeria">Algeria</option>
					<option value="American Samoa">American Samoa</option>
					<option value="Andorra">Andorra</option>
					<option value="Angola">Angola</option>
					<option value="Anguilla">Anguilla</option>
					<option value="Antigua &amp; Barbuda">Antigua &amp; Barbuda</option>
					<option value="Argentina">Argentina</option>
					<option value="Armenia">Armenia</option>
					<option value="Aruba">Aruba</option>
					<option value="Australia">Australia</option>
					<option value="Austria">Austria</option>
					<option value="Azerbaijan">Azerbaijan</option>
					<option value="Bahamas">Bahamas</option>
					<option value="Bahrain">Bahrain</option>
					<option value="Bangladesh">Bangladesh</option>
					<option value="Barbados">Barbados</option>
					<option value="Belarus">Belarus</option>
					<option value="Belgium">Belgium</option>
					<option value="Belize">Belize</option>
					<option value="Benin">Benin</option>
					<option value="Bermuda">Bermuda</option>
					<option value="Bhutan">Bhutan</option>
					<option value="Bolivia">Bolivia</option>
					<option value="Bonaire">Bonaire</option>
					<option value="Bosnia &amp; Herzegovina">Bosnia &amp; Herzegovina</option>
					<option value="Botswana">Botswana</option>
					<option value="Brazil">Brazil</option>
					<option value="British Indian Ocean Ter">British Indian Ocean Ter</option>
					<option value="Brunei">Brunei</option>
					<option value="Bulgaria">Bulgaria</option>
					<option value="Burkina Faso">Burkina Faso</option>
					<option value="Burundi">Burundi</option>
					<option value="Cambodia">Cambodia</option>
					<option value="Cameroon">Cameroon</option>
					<option value="Canada">Canada</option>
					<option value="Canary Islands">Canary Islands</option>
					<option value="Cape Verde">Cape Verde</option>
					<option value="Cayman Islands">Cayman Islands</option>
					<option value="Central African Republic">Central African Republic</option>
					<option value="Chad">Chad</option>
					<option value="Channel Islands">Channel Islands</option>
					<option value="Chile">Chile</option>
					<option value="China">China</option>
					<option value="Christmas Island">Christmas Island</option>
					<option value="Cocos Island">Cocos Island</option>
					<option value="Colombia">Colombia</option>
					<option value="Comoros">Comoros</option>
					<option value="Congo">Congo</option>
					<option value="Cook Islands">Cook Islands</option>
					<option value="Costa Rica">Costa Rica</option>
					<option value="Cote DIvoire">Cote D'Ivoire</option>
					<option value="Croatia">Croatia</option>
					<option value="Cuba">Cuba</option>
					<option value="Curaco">Curacao</option>
					<option value="Cyprus">Cyprus</option>
					<option value="Czech Republic">Czech Republic</option>
					<option value="Denmark">Denmark</option>
					<option value="Djibouti">Djibouti</option>
					<option value="Dominica">Dominica</option>
					<option value="Dominican Republic">Dominican Republic</option>
					<option value="East Timor">East Timor</option>
					<option value="Ecuador">Ecuador</option>
					<option value="Egypt">Egypt</option>
					<option value="El Salvador">El Salvador</option>
					<option value="Equatorial Guinea">Equatorial Guinea</option>
					<option value="Eritrea">Eritrea</option>
					<option value="Estonia">Estonia</option>
					<option value="Ethiopia">Ethiopia</option>
					<option value="Falkland Islands">Falkland Islands</option>
					<option value="Faroe Islands">Faroe Islands</option>
					<option value="Fiji">Fiji</option>
					<option value="Finland">Finland</option>
					<option value="France">France</option>
					<option value="French Guiana">French Guiana</option>
					<option value="French Polynesia">French Polynesia</option>
					<option value="French Southern Ter">French Southern Ter</option>
					<option value="Gabon">Gabon</option>
					<option value="Gambia">Gambia</option>
					<option value="Georgia">Georgia</option>
					<option value="Germany">Germany</option>
					<option value="Ghana">Ghana</option>
					<option value="Gibraltar">Gibraltar</option>
					<option value="Great Britain">Great Britain</option>
					<option value="Greece">Greece</option>
					<option value="Greenland">Greenland</option>
					<option value="Grenada">Grenada</option>
					<option value="Guadeloupe">Guadeloupe</option>
					<option value="Guam">Guam</option>
					<option value="Guatemala">Guatemala</option>
					<option value="Guinea">Guinea</option>
					<option value="Guyana">Guyana</option>
					<option value="Haiti">Haiti</option>
					<option value="Hawaii">Hawaii</option>
					<option value="Honduras">Honduras</option>
					<option value="Hong Kong">Hong Kong</option>
					<option value="Hungary">Hungary</option>
					<option value="Iceland">Iceland</option>
					<option value="India">India</option>
					<option value="Indonesia">Indonesia</option>
					<option value="Iran">Iran</option>
					<option value="Iraq">Iraq</option>
					<option value="Ireland">Ireland</option>
					<option value="Isle of Man">Isle of Man</option>
					<option value="Israel">Israel</option>
					<option value="Italy">Italy</option>
					<option value="Jamaica">Jamaica</option>
					<option value="Japan">Japan</option>
					<option value="Jordan">Jordan</option>
					<option value="Kazakhstan">Kazakhstan</option>
					<option value="Kenya">Kenya</option>
					<option value="Kiribati">Kiribati</option>
					<option value="Korea North">Korea North</option>
					<option value="Korea Sout">Korea South</option>
					<option value="Kuwait">Kuwait</option>
					<option value="Kyrgyzstan">Kyrgyzstan</option>
					<option value="Laos">Laos</option>
					<option value="Latvia">Latvia</option>
					<option value="Lebanon">Lebanon</option>
					<option value="Lesotho">Lesotho</option>
					<option value="Liberia">Liberia</option>
					<option value="Libya">Libya</option>
					<option value="Liechtenstein">Liechtenstein</option>
					<option value="Lithuania">Lithuania</option>
					<option value="Luxembourg">Luxembourg</option>
					<option value="Macau">Macau</option>
					<option value="Macedonia">Macedonia</option>
					<option value="Madagascar">Madagascar</option>
					<option value="Malaysia">Malaysia</option>
					<option value="Malawi">Malawi</option>
					<option value="Maldives">Maldives</option>
					<option value="Mali">Mali</option>
					<option value="Malta">Malta</option>
					<option value="Marshall Islands">Marshall Islands</option>
					<option value="Martinique">Martinique</option>
					<option value="Mauritania">Mauritania</option>
					<option value="Mauritius">Mauritius</option>
					<option value="Mayotte">Mayotte</option>
					<option value="Mexico">Mexico</option>
					<option value="Midway Islands">Midway Islands</option>
					<option value="Moldova">Moldova</option>
					<option value="Monaco">Monaco</option>
					<option value="Mongolia">Mongolia</option>
					<option value="Montserrat">Montserrat</option>
					<option value="Morocco">Morocco</option>
					<option value="Mozambique">Mozambique</option>
					<option value="Myanmar">Myanmar</option>
					<option value="Nambia">Nambia</option>
					<option value="Nauru">Nauru</option>
					<option value="Nepal">Nepal</option>
					<option value="Netherland Antilles">Netherland Antilles</option>
					<option value="Netherlands">Netherlands (Holland, Europe)</option>
					<option value="Nevis">Nevis</option>
					<option value="New Caledonia">New Caledonia</option>
					<option value="New Zealand">New Zealand</option>
					<option value="Nicaragua">Nicaragua</option>
					<option value="Niger">Niger</option>
					<option value="Nigeria">Nigeria</option>
					<option value="Niue">Niue</option>
					<option value="Norfolk Island">Norfolk Island</option>
					<option value="Norway">Norway</option>
					<option value="Oman">Oman</option>
					<option value="Pakistan">Pakistan</option>
					<option value="Palau Island">Palau Island</option>
					<option value="Palestine">Palestine</option>
					<option value="Panama">Panama</option>
					<option value="Papua New Guinea">Papua New Guinea</option>
					<option value="Paraguay">Paraguay</option>
					<option value="Peru">Peru</option>
					<option value="Phillipines">Philippines</option>
					<option value="Pitcairn Island">Pitcairn Island</option>
					<option value="Poland">Poland</option>
					<option value="Portugal">Portugal</option>
					<option value="Puerto Rico">Puerto Rico</option>
					<option value="Qatar">Qatar</option>
					<option value="Republic of Montenegro">Republic of Montenegro</option>
					<option value="Republic of Serbia">Republic of Serbia</option>
					<option value="Reunion">Reunion</option>
					<option value="Romania">Romania</option>
					<option value="Russia">Russia</option>
					<option value="Rwanda">Rwanda</option>
					<option value="St Barthelemy">St Barthelemy</option>
					<option value="St Eustatius">St Eustatius</option>
					<option value="St Helena">St Helena</option>
					<option value="St Kitts-Nevis">St Kitts-Nevis</option>
					<option value="St Lucia">St Lucia</option>
					<option value="St Maarten">St Maarten</option>
					<option value="St Pierre &amp; Miquelon">St Pierre &amp; Miquelon</option>
					<option value="St Vincent &amp; Grenadines">St Vincent &amp; Grenadines</option>
					<option value="Saipan">Saipan</option>
					<option value="Samoa">Samoa</option>
					<option value="Samoa American">Samoa American</option>
					<option value="San Marino">San Marino</option>
					<option value="Sao Tome & Principe">Sao Tome &amp; Principe</option>
					<option value="Saudi Arabia">Saudi Arabia</option>
					<option value="Senegal">Senegal</option>
					<option value="Seychelles">Seychelles</option>
					<option value="Sierra Leone">Sierra Leone</option>
					<option value="Singapore">Singapore</option>
					<option value="Slovakia">Slovakia</option>
					<option value="Slovenia">Slovenia</option>
					<option value="Solomon Islands">Solomon Islands</option>
					<option value="Somalia">Somalia</option>
					<option value="South Africa">South Africa</option>
					<option value="Spain">Spain</option>
					<option value="Sri Lanka">Sri Lanka</option>
					<option value="Sudan">Sudan</option>
					<option value="Suriname">Suriname</option>
					<option value="Swaziland">Swaziland</option>
					<option value="Sweden">Sweden</option>
					<option value="Switzerland">Switzerland</option>
					<option value="Syria">Syria</option>
					<option value="Tahiti">Tahiti</option>
					<option value="Taiwan">Taiwan</option>
					<option value="Tajikistan">Tajikistan</option>
					<option value="Tanzania">Tanzania</option>
					<option value="Thailand">Thailand</option>
					<option value="Togo">Togo</option>
					<option value="Tokelau">Tokelau</option>
					<option value="Tonga">Tonga</option>
					<option value="Trinidad &amp; Tobago">Trinidad &amp; Tobago</option>
					<option value="Tunisia">Tunisia</option>
					<option value="Turkey">Turkey</option>
					<option value="Turkmenistan">Turkmenistan</option>
					<option value="Turks &amp; Caicos Is">Turks &amp; Caicos Is</option>
					<option value="Tuvalu">Tuvalu</option>
					<option value="Uganda">Uganda</option>
					<option value="Ukraine">Ukraine</option>
					<option value="United Arab Erimates">United Arab Emirates</option>
					<option value="United Kingdom">United Kingdom</option>
					<option value="United States of America">United States of America</option>
					<option value="Uraguay">Uruguay</option>
					<option value="Uzbekistan">Uzbekistan</option>
					<option value="Vanuatu">Vanuatu</option>
					<option value="Vatican City State">Vatican City State</option>
					<option value="Venezuela">Venezuela</option>
					<option value="Vietnam">Vietnam</option>
					<option value="Virgin Islands (Brit)">Virgin Islands (Brit)</option>
					<option value="Virgin Islands (USA)">Virgin Islands (USA)</option>
					<option value="Wake Island">Wake Island</option>
					<option value="Wallis &amp; Futana Is">Wallis &amp; Futana Is</option>
					<option value="Yemen">Yemen</option>
					<option value="Zaire">Zaire</option>
					<option value="Zambia">Zambia</option>
					<option value="Zimbabwe">Zimbabwe</option>
				</select>
				<p><span>&#x7535;&#x8BDD;&#x53F7;&#x7801;*</span></p>
				<input type="text" name="countryCode">
				<input type="text" name="areaCode">
				<input type="text" name="number">
<!-- 				startlabels -->
				<p><span class="bottomLabel" id="cCode">&#x56FD;&#x5BB6;&#x4EE3;&#x7801;<br />Code</span>
				<p><span class="bottomLabel" id="aCode">&#x533A;&#x57DF;&#x4EE3;&#x7801;<br />Code</span></p>
				<p><span class="bottomLabel" id="number">&#x7F16;&#x53F7;</span></p>
<!-- 				endlabels -->
				<p><span>&#x4F20;&#x771F;</span></p>
				<input type="text" name="countryCodeFax">
				<input type="text" name="areaCodeFax">
				<input type="text" name="numberFax">
<!-- 				startlabels -->
				<p><span class="bottomLabel" id="cCode">&#x56FD;&#x5BB6;&#x4EE3;&#x7801;<br />Code</span>
				<p><span class="bottomLabel" id="aCode">&#x533A;&#x57DF;&#x4EE3;&#x7801;<br />Code</span></p>
				<p><span class="bottomLabel" id="number">&#x7F16;&#x53F7;</span></p>
<!-- 				endlabels -->
				<p><span>Email &#x5730;&#x5740;*</span></p><input type="text" name="email">
				<p><span>&#x516C;&#x53F8;&#x7F51;&#x7AD9;&nbsp;</span></p><input type="text" name="website">
				<p><span>&#x5176;&#x4ED6;&#x8054;&#x7CFB;&#x65B9;&#x5F0F;</span></p><input type="text" name="others">
				<p><span>&#x4FE1;&#x606F;*</span></p><textarea name="message"></textarea>
				<p id="required">* &#x5FC5;&#x586B;&#x5B57;&#x6BB5;</p>
				<?=$this->getRecaptcha()?>
				<input type="submit" name="submit" class="fright clearfix">
			</form>
		</div>
	</div>
</div>