<!--**************************************
				SCRIPT LINKS
    **************************************-->
<?php 
	$url = $_SERVER['REQUEST_URI'];
	$language = explode("/", $url);
?>  
    
<?if($language[1] != 'cn'):?>
	<script src="/Project/1_Website/Design/Main_Layout/scripts/cufon_yui.js" type="text/javascript"></script>
	<script src="/Project/1_Website/Design/Main_Layout/scripts/cufon.js" type="text/javascript"></script>
	<script src="/Project/1_Website/Design/Main_Layout/scripts/global_javascript.js" type="text/javascript"></script>
<?php endif?>

<script src="/Project/1_Website/Design/Main_Layout/scripts/JQueryCorner_plugin.js" type="text/javascript"></script>
