<?php 	$url = $_SERVER['REQUEST_URI'];
		$language = explode("/", $url);
?>

<!DOCTYPE html>
<!--[if IE 9]><html class="no-js ie9" lang="en" xml:lang="en"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9" lang="en" xml:lang="en"><![endif]-->
<!--[if !IE]><!--><html class="no-js" lang="<?=($language[1] == 'cn')? "cn" :  "en" ?>"><!--<![endif]-->

<head>
	<?=metaData::getInstance()->getMetaData(); ?>
		||global_css||
		||local_css||	 	
		||global_javascript_top||
		<script type="text/javascript">
			%%GOOGLE_ANALYTICS%%
			||local_javascript_top||
		</script>
</head>

<body <?=$this->getIdForPage(); ?> class="<?=($language[1] == 'cn')? "chinese" :  "" ?>">

		<div id="wrapper">
			%%HEADER_CONTENT%%
			
			<div id="<?=routes::getInstance()->getCurrentTopLevelPageID()?>_container" class="clearfix">
				%%MAIN_CONTENT%%
			</div>
			
			%%FOOTER_CONTENT%%
		</div>
		
		||dialogues||
		||global_javascript_bottom||
		<script type="text/javascript">
		<?=(userSession::getLanguage() == 'chinese')? "" :  "Cufon.now();" ?>
		
			||local_javascript_bottom||
			
		</script>
</body>
</html>