<div class="upperPanel">
<!-- 	%%SLIDER%% -->
</div>
<div class="lowerPanel">
	<div class="clearfix opaqueNav posAbs">
		<?= navigation::displaySecondLeveNavigationlForPage('primary'); ?>
	</div>
	<div id="aboutContainer" class="clearfix">
		<span id="aboutPointer"class="activePointer"></span>
		<div class="upperContent posRel">
			<?=$this->displayElement('page_content_editor')?>
		</div>
		<div class="lowerContent fleft">
			<div class="orangeContainer fleft">
				<?=$this->displayElement('page_content_editor_1')?>
			</div>	
			<span class="imgHolder fright"<?=$this->displayElement('image_bg')?>></span>
		</div>
	</div>
</div>