<div class="upperPanel">
	%%SLIDER%%
</div>
<div class="lowerPanel">
	<div class="clearfix opaqueNav posAbs">
		<?= navigation::displaySecondLeveNavigationlForPage('primary'); ?>
	</div>
	<div id="businessContainer" class="clearfix">
		<span id="businessPointer" class="activePointer"></span>
		<div class="clearfix mTxl mBxl">
			<div class="upperContent posRel">
				<div id="visionHolder" class="fleft clearfix">
					<?= $this->displayElement('page_content_editor_vision')?>
				</div>
				<span id="visionImg" class="fleft backgroundSet"<?=$this->displayElement('image_bg')?>></span>
				<span id="missionImg" class="fleft backgroundSet"<?=$this->displayElement('image_bg',1)?>></span>
				<div id="missionHolder" class="fleft">
					<?= $this->displayElement('page_content_editor_mission')?>
				</div>
			</div>
		</div>
	</div>
</div>
