%%SLIDER%%
<div class="clearfix opaqueNav posAbs">
	<a href="/corporate-profile/about-spmi">About SPMI</a>
	<a href="/corporate-profile/business-philosophy">Business Philosophy</a>
</div>
<div id="aboutContainer" class="clearfix">
	<span id="businessPointer" class="activePointer"></span>
	<div class="upperContent posRel">
<!-- <!-- 		**********************CMS********************** -->
<!-- 		<h3>Specialty  -->
<!-- 		<br />Pulp  -->
<!-- 		<br />Manufacturing, Inc.</h3> -->
		
<!-- 		<p>Specialty Pulp Manufacturing, Inc. (SPMI), a company based in the Philippines, is engaged in the manufacture, sale, and export of food grade and non-food grade bleached and unbleached specialty pulp, mainly from abaca or Manila Hemp (Musa textilis Nee) as well as other natural long fibers such as sisal (Agave sisalana), kenaf (Hibiscus cannabinus), and jute (Corchorus olitrius).</p> -->
		
<!-- 		<div id="orangeContent posRel" class="fleft"> -->
<!-- 			<div id="orangeWrap"class="posAbs"> -->
			<!-- 		**********************CMS********************** -->
<!-- 				<p>Our group is spearheaded by Ching Bee Trading Corporation (CBT), the biggest trader of abaca fiber in the world and in partnership with various businessmen from the agricultural industry. Being in the business since 1949, CBT brings over half a century of experience in the global abaca trade, giving the company a competitive edge in today’s borderless market.</p> -->
<!-- 			</div> -->
<!-- 		</div> -->
<!-- 		<div class="imgHolder fright"> -->
<!-- 		</div> -->
	</div>
</div>
