<div class="upperPanel">
	%%BANNER%%
</div>
<div class="lowerPanel">
	<div class="clearfix opaqueNav posAbs">
		<?= navigation::displaySecondLeveNavigationlForPage('primary'); ?>
	</div>
	<div id="aboutContainer" class="clearfix">
		<span id="advancePointer"class="activePointer"></span>
		<div class="upperContent posRel">
			<?= $this->displayElement('page_content_editor')?>
		</div>
<!-- 		<div class="lowerContent fleft"> -->
		
<!-- 		</div> -->
	</div>
</div>