<div class="bannerContainer mBxl clearfix">
	<div id="appImg"<?=$this->displayElement('image_bg')?>>
		<div id="appWrap" class="fright">
			<h1><?=$this->displayElement('page_title_element')?></h1>
		</div>
	</div>
</div>
<div class="lowerPanel clearfix">
	<div id="appContainer" class="clearfix fleft">
		<?= $this->displayElement('page_content_editor')?>
	</div>
	<div id="appImages"class="fright clearfix">
		<?= $this->displayElement('page_content_editor_1')?>
	</div>
</div>